#!/bin/sh -e
echo "postrm: $@"

case "$1" in
    remove)
    ;;

    purge)
        echo "Removing \`biblio-api' user ..."
        userdel biblio-api > /dev/null 2>&1
    ;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *)
        echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0