googleBooksCountry: DE

server:
  requestLog:
    appenders: []

  applicationConnectors:
    - type: https
      port: 8090
      keyStorePath: /var/opt/biblio-api/keystore.jks
      keyStorePassword: ZTAyMzk0NTk1MWJiOWF
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8091

database:
  driverClass: org.postgresql.Driver
  user: biblio
  password: ODM4ZGQ2NmNiZmI
  url: jdbc:postgresql://localhost:5432/biblio
  properties:
    charSet: UTF-8
  maxWaitForConnection: 2s
  validationQuery: "/* biblio Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 5
  maxSize: 15
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  level: WARN
  loggers:
    org.ado: INFO
  appenders:
    - type: console
      logFormat: '%date{ISO8601} %-5level[%thread] %logger{10} %m%n'